version: '3.8'
services:
  backend:
    build:
      context: ./Backend
    depends_on:
      - mysqldb
    restart: always
    ports:
      - "8085:8085"
    networks:
      - app-tier

  frontend:
    build:
      context: ./Frontend
    stdin_open: true
    command: sh -c "yarn dev --host"
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
    networks:
      - app-tier

  mysqldb:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - 'mysqldb-data:/var/lib/mysql'
    networks:
      - app-tier

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    networks:
      - app-tier

volumes:
  mysqldb-data:

networks:
  app-tier:
    driver: bridge
