version: '3.8'
services:
  backend:
    build:
      context: ./Backend
    depends_on:
      - mysqldb
    restart: always
    ports:
      - "8085:8085"

  mysqldb:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - 'mysqldb-data:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysqldb
      PMA_PORT: 3306


volumes:
  mysqldb-data:

#  frontend:
#    build:
#      context: ./Frontend
#    ports:
#      - "3000:3000"
#    command: yarn start
