version: '3.8'
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"

#  frontend:
#    build:
#      context: ./Frontend
#    ports:
#      - "3000:3000"
#    command: yarn start
